# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mJdf7o-89wygenlhk2AoUNP1F36BHjaz
"""

pip install streamlit

import streamlit as st

def main():
    st.title('Simple File Upload Test')

    # Create a file uploader widget
    uploaded_file = st.file_uploader("Choose a file to upload", type=['csv', 'txt', 'pdf', 'png', 'jpg'])

    if uploaded_file is not None:
        # Display the file details
        file_details = {"FileName": uploaded_file.name, "FileType": uploaded_file.type}
        st.write(file_details)

        # You can add additional code here to handle the file according to your needs
        # For example, reading the file if it's a CSV or displaying the image if it's an image file.

if __name__ == '__main__':
    main()

